import { defineVisualScenarios } from "./manifest";

import type {
  VisualAssertion,
  VisualDirection,
  VisualGeometry,
  VisualScenario,
  VisualTheme,
} from "./types";

const desktop: VisualGeometry = {
  width: 1440,
  height: 900,
  deviceScaleFactor: 1,
  mobile: false,
};
const comparison = {
  channelTolerance: 4,
  antialiasTolerance: 12,
  maxMismatchRatio: 0.0005,
  maxMaskRatio: 0,
} as const;
const fineInput = {
  pointer: "fine",
  hover: true,
  touchPoints: "preserve",
  acceptance: "browser",
} as const;
const coarseInput = {
  pointer: "coarse",
  hover: false,
  touchPoints: 1,
  acceptance: "mounted-editor",
} as const;
const noSafeArea = { top: 0, right: 0, bottom: 0, left: 0 } as const;

const assertions = (
  direction: VisualDirection,
  extra: readonly VisualAssertion[] = [],
): readonly VisualAssertion[] => [
  {
    id: "editor-root",
    kind: "accessibility",
    selector: ".excalidraw",
    expected: { visible: true },
  },
  {
    id: "editor-bounds",
    kind: "geometry",
    selector: ".excalidraw",
    expected: { noHorizontalOverflow: true, containedByViewport: true },
  },
  {
    id: "responsive-profile",
    kind: "responsive",
    selector: ".excalidraw",
    expected: { direction },
  },
  {
    id: "leaf-marker-policy",
    kind: "marker",
    selector: ".excalidraw",
    expected: { neutralWrappers: true },
  },
  ...extra,
];

const scenario = (
  value: Omit<
    VisualScenario,
    "locale" | "safeArea" | "input" | "masks" | "comparison"
  > &
    Partial<Pick<VisualScenario, "locale" | "safeArea" | "input">>,
): VisualScenario => ({
  locale: value.direction === "rtl" ? "ar-SA" : "en",
  safeArea: noSafeArea,
  input: fineInput,
  masks: [],
  comparison,
  ...value,
});

export const visualScenarios = defineVisualScenarios([
  scenario({
    id: "desktop-welcome",
    artifactStem: "desktop-welcome",
    state: "welcome",
    geometry: desktop,
    theme: "light",
    direction: "ltr",
    setup: "welcome",
    actions: ["focus-primary-action"],
    capture: { selector: ".excalidraw", kind: "editor-root" },
    assertions: assertions("ltr", [
      {
        id: "welcome-actions",
        kind: "accessibility",
        selector: ".welcome-screen-center",
        expected: { visible: true },
      },
      {
        id: "focused-toolbar",
        kind: "focus",
        selector: "[data-testid='toolbar-selection']",
        expected: { visibleFocus: true },
      },
    ]),
    tags: ["desktop", "light", "welcome"],
  }),
  scenario({
    id: "desktop-selected-rectangle",
    artifactStem: "desktop-selected-rectangle",
    state: "selected-rectangle",
    geometry: desktop,
    theme: "light",
    direction: "ltr",
    setup: "selected-rectangle",
    actions: ["open-property-surface"],
    capture: { selector: ".excalidraw", kind: "editor-root" },
    assertions: assertions("ltr", [
      {
        id: "property-leaf",
        kind: "geometry",
        selector: "[data-viewport-ui-name='stylesPanel']",
        expected: { visible: true, containedByEditor: true },
      },
      {
        id: "property-surface",
        kind: "accessibility",
        selector: "[data-floating-surface]",
        expected: { visible: true },
      },
    ]),
    tags: ["desktop", "light", "property"],
  }),
  scenario({
    id: "desktop-active-text",
    artifactStem: "desktop-active-text",
    state: "active-text-editing",
    geometry: desktop,
    theme: "light",
    direction: "ltr",
    setup: "active-text-editing",
    actions: [],
    capture: { selector: ".excalidraw", kind: "editor-root" },
    assertions: assertions("ltr", [
      {
        id: "text-editor",
        kind: "focus",
        selector: ".excalidraw-wysiwyg",
        expected: { active: true, visible: true },
      },
    ]),
    tags: ["desktop", "light", "text"],
  }),
  scenario({
    id: "desktop-toolbar-group",
    artifactStem: "desktop-toolbar-group",
    state: "toolbar-group-open",
    geometry: desktop,
    theme: "light",
    direction: "ltr",
    setup: "welcome",
    actions: ["open-toolbar-overflow"],
    capture: { selector: ".excalidraw", kind: "editor-root" },
    assertions: assertions("ltr", [
      {
        id: "toolbar-menu",
        kind: "routing",
        selector: "[data-surface-kind='toolbar-menu']",
        expected: { visible: true, hitSamples: 3 },
      },
      {
        id: "measurement-rail",
        kind: "geometry",
        selector: ".adaptive-editor-toolbar__measurement",
        expected: { intrinsicWidth: true, ownedOverflow: true },
      },
    ]),
    tags: ["desktop", "light", "toolbar"],
  }),
  scenario({
    id: "desktop-dark-main-menu",
    artifactStem: "desktop-dark-main-menu",
    state: "main-menu-open",
    geometry: desktop,
    theme: "dark",
    direction: "rtl",
    setup: "welcome",
    actions: ["open-main-menu"],
    capture: { selector: ".excalidraw", kind: "editor-root" },
    assertions: assertions("rtl", [
      {
        id: "main-menu",
        kind: "accessibility",
        selector: "[data-testid='dropdown-menu']",
        expected: { role: "menu", visible: true },
      },
      {
        id: "menu-contrast",
        kind: "contrast",
        selector: "[data-testid='dropdown-menu'] [role='menuitem']",
        expected: { ratio: 4.5 },
      },
    ]),
    tags: ["desktop", "dark", "rtl", "menu"],
  }),
  scenario({
    id: "desktop-dark-sidebar-docked",
    artifactStem: "desktop-dark-sidebar-docked",
    state: "sidebar-docked",
    geometry: desktop,
    theme: "dark",
    direction: "rtl",
    setup: "library",
    actions: ["open-docked-sidebar"],
    capture: { selector: ".excalidraw", kind: "editor-root" },
    assertions: assertions("rtl", [
      {
        id: "sidebar",
        kind: "geometry",
        selector: ".sidebar",
        expected: { visible: true, docked: true, containedByEditor: true },
      },
      {
        id: "sidebar-owner",
        kind: "marker",
        selector: ".sidebar",
        expected: { viewportMarker: true },
      },
    ]),
    tags: ["desktop", "dark", "rtl", "sidebar"],
  }),
  scenario({
    id: "desktop-dark-sidebar-overlay",
    artifactStem: "desktop-dark-sidebar-overlay",
    state: "sidebar-overlay",
    geometry: desktop,
    theme: "dark",
    direction: "rtl",
    setup: "library",
    actions: ["open-overlay-sidebar"],
    capture: { selector: ".excalidraw", kind: "editor-root" },
    assertions: assertions("rtl", [
      {
        id: "overlay-sidebar",
        kind: "accessibility",
        selector: ".sidebar",
        expected: { visible: true },
      },
      {
        id: "overlay-marker",
        kind: "marker",
        selector: ".sidebar",
        expected: { viewportMarker: false },
      },
    ]),
    tags: ["desktop", "dark", "rtl", "sidebar"],
  }),
  scenario({
    id: "desktop-library",
    artifactStem: "desktop-library",
    state: "library-content",
    geometry: desktop,
    theme: "light",
    direction: "ltr",
    setup: "library",
    actions: ["open-library"],
    capture: { selector: ".excalidraw", kind: "editor-root" },
    assertions: assertions("ltr", [
      {
        id: "library-content",
        kind: "accessibility",
        selector:
          "[data-testid='library'] [data-library-item-id='visual-library-01']",
        expected: { visible: true, name: "Reusable card" },
      },
    ]),
    tags: ["desktop", "application", "library"],
  }),
  scenario({
    id: "desktop-ai",
    artifactStem: "desktop-ai",
    state: "ai-dialog",
    geometry: desktop,
    theme: "dark",
    direction: "ltr",
    setup: "ai",
    actions: ["open-ai"],
    capture: { selector: ".excalidraw", kind: "editor-root" },
    assertions: assertions("ltr", [
      {
        id: "ai-surface",
        kind: "accessibility",
        selector: "[data-large-surface]",
        expected: { visible: true },
      },
      {
        id: "ai-owned-state",
        kind: "accessibility",
        selector: "[data-large-surface] [role='tab'][aria-selected='true']",
        expected: { visible: true, selected: true },
      },
    ]),
    tags: ["desktop", "application", "ai"],
  }),
  scenario({
    id: "desktop-share",
    artifactStem: "desktop-share",
    state: "share-dialog",
    geometry: desktop,
    theme: "light",
    direction: "ltr",
    setup: "sharing",
    actions: ["open-share"],
    capture: { selector: ".excalidraw-app", kind: "fixture-root" },
    assertions: assertions("ltr", [
      {
        id: "share-surface",
        kind: "accessibility",
        selector: "[data-large-surface]",
        expected: { visible: true },
      },
      {
        id: "share-owned-state",
        kind: "accessibility",
        selector: ".ShareDialog",
        expected: { visible: true },
      },
    ]),
    tags: ["desktop", "application", "share"],
  }),
  scenario({
    id: "desktop-collaboration",
    artifactStem: "desktop-collaboration",
    state: "collaboration-local",
    geometry: desktop,
    theme: "dark",
    direction: "ltr",
    setup: "collaboration",
    actions: [],
    capture: { selector: ".excalidraw", kind: "editor-root" },
    assertions: assertions("ltr", [
      {
        id: "collaborators",
        kind: "accessibility",
        selector: ".UserList",
        expected: { visible: true },
      },
    ]),
    tags: ["desktop", "application", "collaboration"],
  }),
  scenario({
    id: "tablet-dark-library",
    artifactStem: "tablet-dark-library",
    state: "tablet-library-sidebar",
    geometry: { width: 1024, height: 768, deviceScaleFactor: 1, mobile: false },
    theme: "dark",
    direction: "rtl",
    setup: "library",
    actions: ["open-library"],
    capture: { selector: ".excalidraw", kind: "editor-root" },
    assertions: assertions("rtl", [
      {
        id: "tablet-profile",
        kind: "responsive",
        selector: ".excalidraw",
        expected: { adapter: "desktop", tier: "tablet" },
      },
      {
        id: "tablet-library",
        kind: "geometry",
        selector: ".sidebar",
        expected: { visible: true, containedByEditor: true },
      },
      {
        id: "tablet-library-item",
        kind: "accessibility",
        selector:
          "[data-testid='library'] [data-library-item-id='visual-library-01']",
        expected: { visible: true, name: "Reusable card" },
      },
    ]),
    tags: ["tablet", "dark", "rtl", "library"],
  }),
  scenario({
    id: "tablet-light-properties",
    artifactStem: "tablet-light-properties",
    state: "tablet-compact-properties",
    geometry: { width: 768, height: 1024, deviceScaleFactor: 1, mobile: false },
    theme: "light",
    direction: "ltr",
    setup: "selected-rectangle",
    actions: ["open-property-surface"],
    capture: { selector: ".excalidraw", kind: "editor-root" },
    assertions: assertions("ltr", [
      {
        id: "compact-properties",
        kind: "geometry",
        selector: "[data-viewport-ui-name='stylesPanel']",
        expected: { visible: true, containedByEditor: true },
      },
    ]),
    tags: ["tablet", "light", "property"],
  }),
  scenario({
    id: "phone-light-library",
    artifactStem: "phone-light-library",
    state: "phone-library",
    geometry: { width: 375, height: 812, deviceScaleFactor: 1, mobile: true },
    theme: "light",
    direction: "ltr",
    input: coarseInput,
    setup: "library",
    actions: ["open-library"],
    capture: { selector: ".excalidraw", kind: "editor-root" },
    assertions: assertions("ltr", [
      {
        id: "phone-profile",
        kind: "responsive",
        selector: ".excalidraw",
        expected: { adapter: "phone", tier: "phone", density: "touch" },
      },
      {
        id: "phone-library",
        kind: "geometry",
        selector: ".sidebar",
        expected: { visible: true, containedByEditor: true, touchTarget: true },
      },
      {
        id: "phone-library-item",
        kind: "accessibility",
        selector:
          "[data-testid='library'] [data-library-item-id='visual-library-01']",
        expected: { visible: true, name: "Reusable card" },
      },
    ]),
    tags: ["phone", "light", "library"],
  }),
  scenario({
    id: "phone-dark-landscape",
    artifactStem: "phone-dark-landscape",
    state: "short-toolbar-overflow",
    geometry: { width: 812, height: 375, deviceScaleFactor: 1, mobile: true },
    theme: "dark",
    direction: "rtl",
    input: coarseInput,
    setup: "welcome",
    actions: ["exercise-toolbar-final-row"],
    capture: { selector: ".excalidraw", kind: "editor-root" },
    assertions: assertions("rtl", [
      {
        id: "short-profile",
        kind: "responsive",
        selector: ".excalidraw",
        expected: {
          orientation: "landscape",
          blockSize: "short",
          density: "touch",
        },
      },
      {
        id: "overflow-final-row",
        kind: "routing",
        selector:
          "[data-surface-kind='toolbar-menu'] [role^='menuitem']:last-of-type",
        expected: { hitSamples: 3, touchTarget: true },
      },
    ]),
    tags: ["phone", "dark", "rtl", "toolbar", "performance"],
    performance: {
      source: "branch:feat/editor-ui-redesign@responsive-editor-shell",
      allowance:
        "20% interaction and harness allowance over accepted warm medians",
      requiredMetrics: [
        "postSettleCls",
        "longTaskDuration",
        "interactionDuration",
        "harnessDuration",
      ],
      limits: {
        postSettleCls: 0,
        longTaskDuration: 80,
        interactionDuration: 150,
        harnessDuration: 5000,
      },
      samples: 3,
    },
  }),
  scenario({
    id: "embed-dark-help",
    artifactStem: "embed-dark-help",
    state: "safe-area-help",
    geometry: { width: 640, height: 480, deviceScaleFactor: 1, mobile: false },
    theme: "dark",
    direction: "rtl",
    safeArea: { top: 9, right: 21, bottom: 13, left: 33 },
    setup: "welcome",
    actions: ["open-help"],
    capture: { selector: ".excalidraw", kind: "editor-root" },
    assertions: assertions("rtl", [
      {
        id: "help-surface",
        kind: "geometry",
        selector: "[data-large-surface]",
        expected: { visible: true, boundedScroll: true, safeArea: true },
      },
      {
        id: "help-focus",
        kind: "focus",
        selector: "[data-large-surface]",
        expected: { contained: true },
      },
    ]),
    tags: ["embed", "dark", "rtl", "safe-area", "help"],
  }),
  scenario({
    id: "multi-editor-isolation",
    artifactStem: "multi-editor-isolation",
    state: "multi-editor",
    geometry: { width: 1440, height: 900, deviceScaleFactor: 1, mobile: false },
    theme: "light" as VisualTheme,
    direction: "ltr",
    setup: "multi-editor",
    actions: ["exercise-multi-editor-lifecycle"],
    capture: {
      selector: "[data-visual-fixture-root='multi-editor']",
      kind: "fixture-root",
    },
    assertions: [
      {
        id: "two-editors",
        kind: "isolation",
        selector: "[data-visual-fixture-root='multi-editor']",
        expected: {
          count: 2,
          directions: ["ltr", "rtl"],
          themes: ["light", "dark"],
        },
      },
      {
        id: "multi-bounds",
        kind: "geometry",
        selector: "[data-visual-fixture-root='multi-editor']",
        expected: { containedByViewport: true },
      },
    ],
    tags: ["multi-editor", "isolation"],
  }),
  scenario({
    id: "narrow-loading",
    artifactStem: "narrow-loading",
    state: "loading",
    geometry: { width: 375, height: 812, deviceScaleFactor: 1, mobile: true },
    theme: "light",
    direction: "ltr",
    setup: "loading",
    actions: [],
    capture: { selector: ".excalidraw", kind: "editor-root" },
    assertions: assertions("ltr", [
      {
        id: "loading-state",
        kind: "accessibility",
        selector: ".LoadingMessage",
        expected: { visible: true, live: true },
      },
    ]),
    tags: ["recovery", "loading", "phone"],
  }),
  scenario({
    id: "narrow-recoverable-error",
    artifactStem: "narrow-recoverable-error",
    state: "recoverable-error",
    geometry: { width: 375, height: 812, deviceScaleFactor: 1, mobile: true },
    theme: "dark",
    direction: "ltr",
    setup: "recoverable-error",
    actions: [],
    capture: { selector: ".excalidraw", kind: "editor-root" },
    assertions: assertions("ltr", [
      {
        id: "error-dialog",
        kind: "accessibility",
        selector: "[data-large-surface]",
        expected: { visible: true },
      },
      {
        id: "error-contrast",
        kind: "contrast",
        selector: "[data-large-surface]",
        expected: { ratio: 4.5 },
      },
    ]),
    tags: ["recovery", "error", "phone"],
  }),
  scenario({
    id: "top-level-recovery",
    artifactStem: "top-level-recovery",
    state: "top-level-recovery",
    geometry: { width: 640, height: 480, deviceScaleFactor: 1, mobile: false },
    theme: "light",
    direction: "ltr",
    setup: "top-level-recovery",
    actions: ["focus-primary-action"],
    capture: {
      selector: "[data-visual-fixture-root='top-level-recovery']",
      kind: "fixture-root",
    },
    assertions: [
      {
        id: "recovery-owner",
        kind: "accessibility",
        selector:
          "[data-visual-fixture-root='top-level-recovery'] main[aria-labelledby]",
        expected: {
          visible: true,
          role: "main",
          name: "The editor can be reopened",
          labelledBy: "visual-recovery-heading",
          independentOfEditor: true,
        },
      },
      {
        id: "recovery-action",
        kind: "focus",
        selector: "[data-visual-primary-action]",
        expected: { active: true, visibleFocus: true },
      },
      {
        id: "recovery-heading",
        kind: "accessibility",
        selector: "#visual-recovery-heading",
        expected: {
          visible: true,
          role: "heading",
          name: "The editor can be reopened",
        },
      },
      {
        id: "recovery-heading-contrast",
        kind: "contrast",
        selector: "#visual-recovery-heading",
        expected: { ratio: 4.5 },
      },
    ],
    tags: ["recovery", "top-level"],
  }),
] as const);
